[build]
  publish = "public"
  command = "composer install --no-dev --optimize-autoloader && npm run build"

[build.environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.3"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[functions]
  directory = "netlify/functions"